---
title: "ProblemSetExploreManyVariables"
author: "Xiaolong Cao"
date: "July 6, 2016"
output: html_document
---


#Problem Set: Explore Many Variables

##Price Histograms with Facet and Color
```{r price histograms with facet and color}
library(ggplot2) # diamonds data is in this library

summary(diamonds)

# Create a histogram of diamond prices.
# Facet the histogram by diamond color
# and use cut to color the histogram bars.

# The plot should look something like this.
# http://i.imgur.com/b5xyrOu.jpg

# Note: In the link, a color palette of type
# 'qual' was used to color the histogram using
# scale_fill_brewer(type = 'qual')

ggplot(data = diamonds, aes(x = price, fill = cut)) + geom_histogram() + 
  facet_wrap(~color) +
  scale_fill_brewer(type = 'qual') + scale_x_log10()
```

##Price vs. Table Colored by Cut
```{r Price vs. Table Colored by Cut}
# Create a scatterplot of diamond price vs.
# table and color the points by the cut of
# the diamond.

# The plot should look something like this.
# http://i.imgur.com/rQF9jQr.jpg
ggplot(data = diamonds, aes(x = table, y = price, color = cut)) + geom_point() + scale_fill_brewer(type = 'qual')

```
##Price vs. Volume and Diamond Clarity
```{r Price vs. Volume and Diamond Clarity}
# Create a scatterplot of diamond price vs.
# volume (x * y * z) and color the points by
# the clarity of diamonds. Use scale on the y-axis
# to take the log10 of price. You should also
# omit the top 1% of diamond volumes from the plot.
diamonds$volume = diamonds$x * diamonds$y * diamonds$z
ggplot(data = diamonds, aes(x = volume, y = price, color = clarity)) + geom_point(alpha = 0.2) + scale_fill_brewer(type = 'qual') + xlim(0, quantile(diamonds$volume, 0.99)) + scale_y_log10()

```

##Proportion of Friendships Initiated
```{r Proportion of Friendships Initiated}
# Many interesting variables are derived from two or more others.
# For example, we might wonder how much of a person's network on
# a service like Facebook the user actively initiated. Two users
# with the same degree (or number of friends) might be very
# different if one initiated most of those connections on the
# service, while the other initiated very few. So it could be
# useful to consider this proportion of existing friendships that
# the user initiated. This might be a good predictor of how active
# a user is compared with their peers, or other traits, such as
# personality (i.e., is this person an extrovert?).

# Your task is to create a new variable called 'prop_initiated'
# in the Pseudo-Facebook data set. The variable should contain
# the proportion of friendships that the user initiated.

pf = read.csv('E:\\Study\\coursera\\Udacity\\ud651DataAnalysisWithR\\pseudo_facebook.tsv', sep = '\t')
pf$prop_initiated = pf$friendships_initiated / pf$friend_count


```

##prop_initiated vs. tenure
```{r prop_initiated vs. tenure}
# Create a line graph of the median proportion of
# friendships initiated ('prop_initiated') vs.
# tenure and color the line segment by
# year_joined.bucket.
pf$year_joined <- floor(2014 - pf$tenure/365)
table(pf$year_joined)
pf$year_joined.bucket <- cut(pf$year_joined, c(2004, 2009, 2011, 2012,2014))

ggplot(data = pf, aes(x = tenure, y = prop_initiated)) + geom_line(aes(color = year_joined.bucket), stat = 'summary', fun.y = median)

```


##Smoothing prop_initiated vs. tenure
```{r Smoothing prop_initiated vs. tenure}
# Smooth the last plot you created of
# of prop_initiated vs tenure colored by
# year_joined.bucket. You can bin together ranges
# of tenure or add a smoother to the plot.


ggplot(data = pf, aes(x = tenure, y = prop_initiated)) + geom_line(aes(color = year_joined.bucket), stat = 'summary', fun.y = median) + geom_smooth(linetype=3)

ggplot(data = pf, aes(x = 30 * round(tenure / 30), y = prop_initiated)) + geom_line(aes(color = year_joined.bucket), stat = 'summary', fun.y = median)

by(subset(pf$prop_initiated, !is.na(pf$prop_initiated)), subset(pf$year_joined.bucket, !is.na(pf$prop_initiated)), mean)

```


##Price/Carat Binned, Faceted, & Colored
```{r Price/Carat Binned, Faceted, & Colored}
# Create a scatter plot of the price/carat ratio
# of diamonds. The variable x should be
# assigned to cut. The points should be colored
# by diamond color, and the plot should be
# faceted by clarity.

# The plot should look something like this.
# http://i.imgur.com/YzbWkHT.jpg.


ggplot(data = diamonds, aes(x = cut, y = price/carat, color = color)) + geom_jitter() + facet_wrap(~clarity) + scale_color_brewer(type = 'div')

```
